add_subdirectory(sto_hello)
add_subdirectory(sto_conflict)
add_subdirectory(sto_isolation_test)
add_subdirectory(sto_cap_revoke)
add_subdirectory(lucas_hello)
add_subdirectory(lucas_busybox)
add_subdirectory(lucas_fork_test)
add_subdirectory(fork_bomb)
add_subdirectory(antidbg_probe)
add_subdirectory(lucas_udp_send)
add_subdirectory(lucas_pty_test)
add_subdirectory(lucas_python)
add_subdirectory(lucas_pthread)
add_subdirectory(lucas_arch_prctl)
add_subdirectory(procd_unit)
add_subdirectory(sotOs-wal-unit)
add_subdirectory(sotOs-sotnano-unit)
add_subdirectory(sotOs-procd-fork-test)
add_subdirectory(sotOs-procd-pg-test)
add_subdirectory(sotOs-procd-cond-test)
add_subdirectory(sotOs-procd-robust-test)
add_subdirectory(sotOs-shellhook-test)
add_subdirectory(sotOs-stage7-demo)
add_subdirectory(sotOs-syscall-test)
add_subdirectory(sotOs-anomaly-test)
add_subdirectory(sotOs-execmap-test)
add_subdirectory(sotOs-tls-probe)
add_subdirectory(sotOs-wayland-connect)
add_subdirectory(sotOs-wayland-sync)
add_subdirectory(sotOs-wayland-info)
add_subdirectory(sotOs-wl-shm)
add_subdirectory(sotOs-wl-capture-client)
add_subdirectory(assets)
add_subdirectory(sotOs-egress-probe)
add_subdirectory(sotOs-dnsprobe)
add_subdirectory(sotOs-canary-service)
add_subdirectory(sotOs-canary-read)
add_subdirectory(tcc-bin)
add_subdirectory(sotOs-doom)
