/* test_aead.c — golden-vector test for tls13_aead seal/open (ε1 Task 4 + ε3 A4).
 *
 * Goldens generated by an INDEPENDENT library (Python cryptography.hazmat
 * AESGCM) via oracle_aead.py, and the AES-256 primitive is additionally anchored
 * by a NIST CAVP GCM-256 Known-Answer-Test vector below.  Never sourced from our
 * own C output.
 *
 * Parameterized over a {suite, key, iv, seq, inner_type, pt, golden} table so the
 * AES-128-GCM (0x1301, regression) and AES-256-GCM (0x1302, new) suites share the
 * exact same assertions: seal == golden, open round-trips, tag-tamper rejects,
 * truncation/short-record errors. */
#include <assert.h>
#include <stdio.h>
#include <string.h>
#include <stdint.h>
#include <net-synth/tls13.h>
#include <net-synth/tls13_aead.h>
#include <bearssl.h>

/* ── keys / ivs (oracle_aead.py: KEY16=range(16), KEY32=range(32), IV12=range(12)) */
static const uint8_t KEY16[16] = {0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15};
static const uint8_t KEY32[32] = {0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,
                                  16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31};
static const uint8_t IV[12]    = {0,1,2,3,4,5,6,7,8,9,10,11};

/* ── 0x1301 (AES-128-GCM) framed goldens (regression — unchanged from ε1). */
static const uint8_t REC_128_0[] = {  /* seq=0, "hello", inner_type=0x16 */
    0x17,0x03,0x03,0x00,0x16,
    0xfb,0x09,0xcb,0xa2,0x09,0x0d,0x58,0xe7,0x3c,0x31,0x56,0x33,
    0x52,0x43,0x3d,0x33,0xc8,0xbf,0xd9,0xf9,0x86,0xeb
};
static const uint8_t REC_128_1[] = {  /* seq=1, "world", inner_type=0x17 */
    0x17,0x03,0x03,0x00,0x16,
    0xb6,0x56,0x64,0xfe,0x00,0x08,0x06,0xf7,0x42,0x06,0x17,0xf2,
    0x54,0x50,0x34,0x4f,0x61,0x01,0x74,0xeb,0x25,0xaf
};

/* ── 0x1302 (AES-256-GCM) framed goldens (NEW — oracle_aead.py --cipher aes256). */
static const uint8_t REC_256_0[] = {  /* seq=0, "hello", inner_type=0x16 */
    0x17,0x03,0x03,0x00,0x16,
    0x2f,0x67,0xba,0x77,0xaa,0xf3,0xe9,0xd7,0x88,0xd1,0x9e,0x56,
    0x9d,0x63,0x2a,0xf0,0xfa,0x54,0xf7,0x5f,0xaf,0xfb
};
static const uint8_t REC_256_1[] = {  /* seq=1, "world", inner_type=0x17 */
    0x17,0x03,0x03,0x00,0x16,
    0xd1,0xb7,0xbb,0x2c,0x6b,0xcf,0xc4,0x73,0x6d,0xce,0x32,0x80,
    0x92,0x89,0xd0,0x9e,0x32,0x73,0x2c,0x73,0xa9,0x26
};

/* ── 0x1303 (ChaCha20-Poly1305) framed goldens (NEW — oracle_aead.py
 * --cipher chacha20; independent Python cryptography ChaCha20Poly1305). */
static const uint8_t REC_CHA_0[] = {  /* seq=0, "hello", inner_type=0x16 */
    0x17,0x03,0x03,0x00,0x16,
    0xe1,0x9e,0x64,0x6c,0x46,0x01,0x10,0x91,0xc0,0xcc,0x2e,0xbe,
    0xf5,0xdf,0x6d,0x82,0x9b,0x7b,0x2e,0x59,0x89,0xe6
};
static const uint8_t REC_CHA_1[] = {  /* seq=1, "world", inner_type=0x17 */
    0x17,0x03,0x03,0x00,0x16,
    0x31,0xce,0x39,0x00,0xd0,0x71,0x8a,0xc8,0x5c,0x42,0xe8,0xbd,
    0xdf,0x92,0x5c,0x55,0xc1,0x60,0x21,0x65,0x26,0x85
};

typedef struct {
    uint16_t       suite_id;
    const uint8_t *key;
    uint64_t       seq;
    uint8_t        inner_type;
    const char    *pt;
    size_t         pt_len;
    const uint8_t *golden;
    size_t         golden_len;
} aead_vec_t;

static const aead_vec_t VECS[] = {
    { 0x1301, KEY16, 0, 0x16, "hello", 5, REC_128_0, sizeof REC_128_0 },
    { 0x1301, KEY16, 1, 0x17, "world", 5, REC_128_1, sizeof REC_128_1 },
    { 0x1302, KEY32, 0, 0x16, "hello", 5, REC_256_0, sizeof REC_256_0 },
    { 0x1302, KEY32, 1, 0x17, "world", 5, REC_256_1, sizeof REC_256_1 },
    { 0x1303, KEY32, 0, 0x16, "hello", 5, REC_CHA_0, sizeof REC_CHA_0 },
    { 0x1303, KEY32, 1, 0x17, "world", 5, REC_CHA_1, sizeof REC_CHA_1 },
};

/* ── NIST CAVP AES-256 GCM KAT (gcmEncryptExtIV256.rsp, 96-bit IV / 128-bit tag).
 * Anchors the BARE AES-256-GCM primitive (br_gcm over AES-256) BEFORE any TLS
 * framing, using BearSSL directly so a key-truncation regression cannot hide. */
static void nist_gcm256_kat(void)
{
    static const uint8_t key[32] = {
        0x92,0xe1,0x1d,0xcd,0xaa,0x86,0x6f,0x5c,0xe7,0x90,0xfd,0x24,0x50,0x1f,0x92,0x50,
        0x9a,0xac,0xf4,0xcb,0x8b,0x13,0x39,0xd5,0x0c,0x9c,0x12,0x40,0x93,0x5d,0xd0,0x8b};
    static const uint8_t iv[12]  = {0xac,0x93,0xa1,0xa6,0x14,0x52,0x99,0xbd,0xe9,0x02,0xf2,0x1a};
    static const uint8_t aad[16] = {0x1e,0x08,0x89,0x01,0x6f,0x67,0x60,0x1c,0x8e,0xbe,0xa4,0x94,0x3b,0xc2,0x3a,0xd6};
    static const uint8_t pt[16]  = {0x2d,0x71,0xbc,0xfa,0x91,0x4e,0x4a,0xc0,0x45,0xb2,0xaa,0x60,0x95,0x5f,0xad,0x24};
    static const uint8_t ct[16]  = {0x89,0x95,0xae,0x2e,0x6d,0xf3,0xdb,0xf9,0x6f,0xac,0x7b,0x71,0x37,0xba,0xe6,0x7f};
    static const uint8_t tag[16] = {0xec,0xa5,0xaa,0x77,0xd5,0x1d,0x4a,0x0a,0x14,0xd9,0xc5,0x1e,0x1d,0xa4,0x74,0xab};

    uint8_t buf[16], gtag[16];
    memcpy(buf, pt, 16);

    br_aes_ct64_ctr_keys bc;
    br_aes_ct64_ctr_init(&bc, key, 32);   /* AES-256: 32-byte key */
    br_gcm_context gc;
    br_gcm_init(&gc, &bc.vtable, br_ghash_ctmul64);
    br_gcm_reset(&gc, iv, 12);
    br_gcm_aad_inject(&gc, aad, 16);
    br_gcm_flip(&gc);
    br_gcm_run(&gc, 1 /* encrypt */, buf, 16);
    br_gcm_get_tag(&gc, gtag);

    assert(memcmp(buf, ct, 16) == 0);
    assert(memcmp(gtag, tag, 16) == 0);
    printf("NIST CAVP GCM-256 KAT OK\n");
}

/* ── RFC 7539 §2.8.2 canonical AEAD_CHACHA20_POLY1305 vector.
 * Anchors the BARE ChaCha20-Poly1305 primitive (br_poly1305_ctmul_run over
 * br_chacha20_ct_run) BEFORE any TLS framing, against the gold-standard published
 * vector — this removes the oracle-self-agreement risk for the new AEAD. */
static void rfc7539_chacha_kat(void)
{
    static const uint8_t key[32] = {
        0x80,0x81,0x82,0x83,0x84,0x85,0x86,0x87,0x88,0x89,0x8a,0x8b,0x8c,0x8d,0x8e,0x8f,
        0x90,0x91,0x92,0x93,0x94,0x95,0x96,0x97,0x98,0x99,0x9a,0x9b,0x9c,0x9d,0x9e,0x9f};
    static const uint8_t iv[12]  = {0x07,0x00,0x00,0x00,0x40,0x41,0x42,0x43,0x44,0x45,0x46,0x47};
    static const uint8_t aad[12] = {0x50,0x51,0x52,0x53,0xc0,0xc1,0xc2,0xc3,0xc4,0xc5,0xc6,0xc7};
    static const uint8_t pt[114] = {
        "Ladies and Gentlemen of the class of '99: If I could offer you only one tip "
        "for the future, sunscreen would be it."};
    static const uint8_t ct[114] = {
        0xd3,0x1a,0x8d,0x34,0x64,0x8e,0x60,0xdb,0x7b,0x86,0xaf,0xbc,0x53,0xef,0x7e,0xc2,
        0xa4,0xad,0xed,0x51,0x29,0x6e,0x08,0xfe,0xa9,0xe2,0xb5,0xa7,0x36,0xee,0x62,0xd6,
        0x3d,0xbe,0xa4,0x5e,0x8c,0xa9,0x67,0x12,0x82,0xfa,0xfb,0x69,0xda,0x92,0x72,0x8b,
        0x1a,0x71,0xde,0x0a,0x9e,0x06,0x0b,0x29,0x05,0xd6,0xa5,0xb6,0x7e,0xcd,0x3b,0x36,
        0x92,0xdd,0xbd,0x7f,0x2d,0x77,0x8b,0x8c,0x98,0x03,0xae,0xe3,0x28,0x09,0x1b,0x58,
        0xfa,0xb3,0x24,0xe4,0xfa,0xd6,0x75,0x94,0x55,0x85,0x80,0x8b,0x48,0x31,0xd7,0xbc,
        0x3f,0xf4,0xde,0xf0,0x8e,0x4b,0x7a,0x9d,0xe5,0x76,0xd2,0x65,0x86,0xce,0xc6,0x4b,
        0x61,0x16};
    static const uint8_t tag[16] = {
        0x1a,0xe1,0x0b,0x59,0x4f,0x09,0xe2,0x6a,0x7e,0x90,0x2e,0xcb,0xd0,0x60,0x06,0x91};

    /* --- encrypt: raw primitive must produce the exact RFC ciphertext+tag. --- */
    uint8_t buf[114], gtag[16];
    memcpy(buf, pt, 114);
    br_poly1305_ctmul_run(key, iv, buf, 114, aad, 12, gtag,
                          &br_chacha20_ct_run, 1 /* encrypt */);
    assert(memcmp(buf, ct, 114) == 0);
    assert(memcmp(gtag, tag, 16) == 0);

    /* --- decrypt round-trip: recover the plaintext + recompute the same tag. --- */
    uint8_t dbuf[114], dtag[16];
    memcpy(dbuf, ct, 114);
    br_poly1305_ctmul_run(key, iv, dbuf, 114, aad, 12, dtag,
                          &br_chacha20_ct_run, 0 /* decrypt */);
    assert(memcmp(dbuf, pt, 114) == 0);
    assert(memcmp(dtag, tag, 16) == 0);

    printf("RFC 7539 §2.8.2 ChaCha20-Poly1305 KAT OK\n");
}

int main(void)
{
    uint8_t out[256];
    uint8_t pt[256];
    size_t  pt_len;
    uint8_t inner_type;

    /* (0) Bare-primitive anchors: AES-256-GCM (NIST CAVP) + ChaCha20-Poly1305
     * (RFC 7539 §2.8.2) — both BEFORE any TLS framing. */
    nist_gcm256_kat();
    rfc7539_chacha_kat();

    for (size_t i = 0; i < sizeof VECS / sizeof VECS[0]; i++) {
        const aead_vec_t *v = &VECS[i];
        const tls13_suite_t *su = tls13_suite_by_id(v->suite_id);
        assert(su != NULL);

        /* --- seal == golden --- */
        size_t rec_len = tls13_record_seal(su, v->key, IV, v->seq, v->inner_type,
                                           (const uint8_t *)v->pt, v->pt_len,
                                           out, sizeof out);
        assert(rec_len == v->golden_len);
        assert(memcmp(out, v->golden, rec_len) == 0);
        printf("suite %#06x seal seq=%llu OK\n", v->suite_id,
               (unsigned long long)v->seq);

        /* --- open round-trips the golden --- */
        int r = tls13_record_open(su, v->key, IV, v->seq, v->golden, v->golden_len,
                                  pt, sizeof pt, &pt_len, &inner_type);
        assert(r == 0);
        assert(pt_len == v->pt_len);
        assert(inner_type == v->inner_type);
        assert(memcmp(pt, v->pt, v->pt_len) == 0);
        printf("suite %#06x open seq=%llu OK\n", v->suite_id,
               (unsigned long long)v->seq);

        /* --- tag-tamper must fail (flip last tag byte) --- */
        uint8_t tampered[64];
        assert(v->golden_len <= sizeof tampered);
        memcpy(tampered, v->golden, v->golden_len);
        tampered[v->golden_len - 1] ^= 0xff;   /* flip last tag byte */
        r = tls13_record_open(su, v->key, IV, v->seq, tampered, v->golden_len,
                              pt, sizeof pt, &pt_len, &inner_type);
        assert(r == -1);
        printf("suite %#06x tag-tamper rejected OK\n", v->suite_id);

        /* --- ciphertext-byte tamper must fail (single-bit flip of the first
         * ciphertext byte at offset 5 — the AEAD's auth must reject it). --- */
        memcpy(tampered, v->golden, v->golden_len);
        tampered[5] ^= 0x01;                    /* single-bit flip in ciphertext */
        r = tls13_record_open(su, v->key, IV, v->seq, tampered, v->golden_len,
                              pt, sizeof pt, &pt_len, &inner_type);
        assert(r == -1);
        printf("suite %#06x ct-tamper rejected OK\n", v->suite_id);

        /* --- truncated record (length-inconsistent) must fail --- */
        r = tls13_record_open(su, v->key, IV, v->seq, v->golden, v->golden_len - 1,
                              pt, sizeof pt, &pt_len, &inner_type);
        assert(r == -1);
        printf("suite %#06x truncated rejected OK\n", v->suite_id);

        /* --- too-short record (< 5+16) must fail --- */
        {
            uint8_t tmp[64]; size_t tl; uint8_t it;
            assert(tls13_record_open(su, v->key, IV, v->seq,
                                     (const uint8_t[]){0x17,0x03,0x03,0x00,0x10}, 5,
                                     tmp, sizeof tmp, &tl, &it) == -1);
            printf("suite %#06x too-short rejected OK\n", v->suite_id);
        }
    }

    /* --- NULL suite defaults to 0x1301 (pre-A5 bridge): byte-identical AES-128. */
    {
        size_t rec_len = tls13_record_seal(NULL, KEY16, IV, 0, 0x16,
                                           (const uint8_t *)"hello", 5,
                                           out, sizeof out);
        assert(rec_len == sizeof REC_128_0);
        assert(memcmp(out, REC_128_0, rec_len) == 0);
        int r = tls13_record_open(NULL, KEY16, IV, 0, REC_128_0, sizeof REC_128_0,
                                  pt, sizeof pt, &pt_len, &inner_type);
        assert(r == 0 && pt_len == 5 && inner_type == 0x16 &&
               memcmp(pt, "hello", 5) == 0);
        printf("NULL-suite defaults to 0x1301 OK\n");
    }

    printf("test_aead OK\n");
    return 0;
}
